version: 0.0.{build}
image: Visual Studio 2017
build_script:
- ps: >-
    ./install_dotnet.ps1
- cmd: >-
    dotnet --version
- cmd: >-
    dotnet build ExtCore.sln
- cmd: >-
    dotnet test ExtCore.Tests\ExtCore.Tests.fsproj
- cmd >-
    dotnet pack
test: off
